language: php

php:
    - 7.1
    - 7.2
    - hhvm

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - DOCKER_BUILD=false
        - SYMFONY_DEPRECATIONS_HELPER=strict
        - SYMFONY_VERSION=4.1.*

install: travis/install.sh
script: travis/script.sh
after_success: travis/success.sh

matrix:
    include:
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*@dev
    allow_failures:
        - env: SYMFONY_VERSION=4.0.*@dev

notifications:
    email: craig@craigrayner.com
